/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../..";

export interface GetSnippetTemplate {
    /**
     * The organization to create snippets for.
     *
     */
    orgId: FernInternal.OrgId;
    /**
     * The API name.
     *
     */
    apiId: FernInternal.ApiId;
    sdk: FernInternal.Sdk;
    endpointId: FernInternal.EndpointIdentifier;
}
