/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../../index";

/**
 * @example
 *     {
 *         orgId: "string",
 *         apiId: "string",
 *         sdk: {
 *             type: "typescript",
 *             package: "string",
 *             version: "string"
 *         },
 *         endpointId: {
 *             path: "string",
 *             method: FernInternal.EndpointMethod.Put
 *         }
 *     }
 *
 * @example
 *     {
 *         orgId: "string",
 *         apiId: "string",
 *         sdk: {
 *             type: "typescript",
 *             package: "string",
 *             version: "string"
 *         },
 *         endpointId: {
 *             path: "string",
 *             method: FernInternal.EndpointMethod.Put
 *         }
 *     }
 *
 * @example
 *     {
 *         orgId: "string",
 *         apiId: "string",
 *         sdk: {
 *             type: "typescript",
 *             package: "string",
 *             version: "string"
 *         },
 *         endpointId: {
 *             path: "string",
 *             method: FernInternal.EndpointMethod.Put
 *         }
 *     }
 */
export interface GetSnippetTemplate {
    /**
     * The organization to create snippets for.
     *
     */
    orgId: FernInternal.OrgId;
    /**
     * The API name.
     *
     */
    apiId: FernInternal.ApiId;
    sdk: FernInternal.Sdk;
    endpointId: FernInternal.EndpointIdentifier;
}
