/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../index";

/**
 * @example
 *     {
 *         orgId: "string",
 *         apiId: "string",
 *         sdk: {
 *             type: "typescript",
 *             package: "string",
 *             version: "string"
 *         },
 *         endpointId: {
 *             path: "string",
 *             method: Fern.HttpMethod.Get,
 *             identifierOverride: "string"
 *         }
 *     }
 */
export interface GetSnippetTemplate {
    /**
     * The organization to create snippets for.
     *
     */
    orgId: Fern.OrgId;
    /**
     * The API name.
     *
     */
    apiId: Fern.ApiId;
    sdk: Fern.SdkRequest;
    endpointId: Fern.EndpointIdentifier;
}
