/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../..";

export interface RegisterSnippetTemplateRequest {
    /**
     * The organization to create snippets for.
     *
     */
    orgId: Fern.OrgId;
    /**
     * The API name.
     *
     */
    apiId: Fern.ApiId;
    apiDefinitionId: Fern.ApiDefinitionId;
    snippet: Fern.SnippetRegistryEntry;
}
