/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../../index";

/**
 * @example
 *     {
 *         orgId: "string",
 *         apiId: "string",
 *         apiDefinitionId: "d5e9c84f-c2b2-4bf4-b4b0-7ffd7a9ffc32",
 *         snippet: {
 *             sdk: {
 *                 type: "typescript",
 *                 package: "string",
 *                 version: "string"
 *             },
 *             endpointId: {
 *                 path: "string",
 *                 method: FernInternal.EndpointMethod.Put
 *             },
 *             snippetTemplate: {
 *                 type: "v1",
 *                 clientInstantiation: "string",
 *                 functionInvocation: {
 *                     type: "generic",
 *                     imports: ["string"],
 *                     isOptional: true,
 *                     templateString: "string",
 *                     templateInputs: [{
 *                             type: "template",
 *                             value: {
 *                                 "key": "value"
 *                             }
 *                         }],
 *                     inputDelimiter: "string"
 *                 }
 *             }
 *         }
 *     }
 */
export interface RegisterSnippetTemplateRequest {
    /**
     * The organization to create snippets for.
     *
     */
    orgId: FernInternal.OrgId;
    /**
     * The API name.
     *
     */
    apiId: FernInternal.ApiId;
    apiDefinitionId: FernInternal.ApiDefinitionId;
    snippet: FernInternal.SnippetRegistryEntry;
}
