/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const ApiIdNotFound: core.serialization.Schema<serializers.snippets.ApiIdNotFound.Raw, string> =
    core.serialization.string();

export declare namespace ApiIdNotFound {
    type Raw = string;
}
