/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const ApiIdRequiredError: core.serialization.Schema<serializers.snippets.ApiIdRequiredError.Raw, string> =
    core.serialization.string();

export declare namespace ApiIdRequiredError {
    type Raw = string;
}
