/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const EndpointNotFound: core.serialization.Schema<serializers.snippets.EndpointNotFound.Raw, string> =
    core.serialization.string();

export declare namespace EndpointNotFound {
    type Raw = string;
}
