/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const InvalidPageError: core.serialization.Schema<serializers.snippets.InvalidPageError.Raw, string> =
    core.serialization.string();

export declare namespace InvalidPageError {
    type Raw = string;
}
