/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const OrgIdNotFound: core.serialization.Schema<serializers.snippets.OrgIdNotFound.Raw, string> =
    core.serialization.string();

export declare namespace OrgIdNotFound {
    type Raw = string;
}
