/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const OrgIdRequiredError: core.serialization.Schema<serializers.OrgIdRequiredError.Raw, string> =
    core.serialization.string();

export declare namespace OrgIdRequiredError {
    type Raw = string;
}
