/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Fern from "../../../../../api";
import * as core from "../../../../../core";
import { OrgId } from "../../../commons/types/OrgId";
import { ApiId } from "../../../commons/types/ApiId";
import { Sdk } from "../../../../types/Sdk";
import { EndpointIdentifier } from "../../../../types/EndpointIdentifier";

export const GetSnippetTemplate: core.serialization.Schema<
    serializers.GetSnippetTemplate.Raw,
    Fern.GetSnippetTemplate
> = core.serialization.object({
    orgId: OrgId,
    apiId: ApiId,
    sdk: Sdk,
    endpointId: EndpointIdentifier,
});

export declare namespace GetSnippetTemplate {
    interface Raw {
        orgId: OrgId.Raw;
        apiId: ApiId.Raw;
        sdk: Sdk.Raw;
        endpointId: EndpointIdentifier.Raw;
    }
}
