/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class UserNotInOrgError extends errors.FernError {
    constructor(body: string) {
        super({
            message: "UserNotInOrgError",
            statusCode: 403,
            body: body,
        });
        Object.setPrototypeOf(this, UserNotInOrgError.prototype);
    }
}
