/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as core from "../../core";

export const OrgIdAndApiIdNotFound: core.serialization.Schema<serializers.OrgIdAndApiIdNotFound.Raw, string> =
    core.serialization.string();

export declare namespace OrgIdAndApiIdNotFound {
    type Raw = string;
}
