/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as core from "../../core";

export const SdkNotFound: core.serialization.Schema<serializers.SdkNotFound.Raw, string> = core.serialization.string();

export declare namespace SdkNotFound {
    type Raw = string;
}
