/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Fern from "../../../../../api";
import * as core from "../../../../../core";

export const GetSnippetRequest: core.serialization.Schema<
    serializers.snippets.GetSnippetRequest.Raw,
    Fern.snippets.GetSnippetRequest
> = core.serialization.object({
    apiId: core.serialization.lazy(async () => (await import("../../../..")).snippets.ApiId).optional(),
    sdks: core.serialization
        .list(core.serialization.lazy(async () => (await import("../../../..")).snippets.Sdk))
        .optional(),
    endpoint: core.serialization.lazyObject(async () => (await import("../../../..")).snippets.EndpointIdentifier),
});

export declare namespace GetSnippetRequest {
    interface Raw {
        apiId?: serializers.snippets.ApiId.Raw | null;
        sdks?: serializers.snippets.Sdk.Raw[] | null;
        endpoint: serializers.snippets.EndpointIdentifier.Raw;
    }
}
