/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";
import { PayloadLocation } from "./PayloadLocation";

export const PayloadInput: core.serialization.ObjectSchema<serializers.PayloadInput.Raw, Fern.PayloadInput> =
    core.serialization.object({
        location: PayloadLocation,
        path: core.serialization.string().optional(),
    });

export declare namespace PayloadInput {
    interface Raw {
        location: PayloadLocation.Raw;
        path?: string | null;
    }
}
