/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const PayloadLocation: core.serialization.Schema<serializers.PayloadLocation.Raw, Fern.PayloadLocation> =
    core.serialization.enum_(["BODY", "QUERY", "PATH", "HEADERS", "RELATIVE"]);

export declare namespace PayloadLocation {
    type Raw = "BODY" | "QUERY" | "PATH" | "HEADERS" | "RELATIVE";
}
