/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const SnippetTemplate: core.serialization.ObjectSchema<serializers.SnippetTemplate.Raw, Fern.SnippetTemplate> =
    core.serialization.object({
        clientInstantiation: core.serialization.string(),
        functionInvocation: core.serialization.lazy(async () => (await import("../../..")).Template),
    });

export declare namespace SnippetTemplate {
    interface Raw {
        clientInstantiation: string;
        functionInvocation: serializers.Template.Raw;
    }
}
