/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";
import { SnippetTemplate } from "./SnippetTemplate";

export const VersionedSnippetTemplate: core.serialization.Schema<
    serializers.VersionedSnippetTemplate.Raw,
    Fern.VersionedSnippetTemplate
> = core.serialization
    .union("type", {
        v1: SnippetTemplate,
    })
    .transform<Fern.VersionedSnippetTemplate>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace VersionedSnippetTemplate {
    type Raw = VersionedSnippetTemplate.V1;

    interface V1 extends SnippetTemplate.Raw {
        type: "v1";
    }
}
