/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as Fern from "../../../api";
import * as core from "../../../core";
import { OrgId } from "../../resources/commons/types/OrgId";
import { ApiId } from "../../resources/commons/types/ApiId";
import { Sdk } from "../../types/Sdk";
import { EndpointIdentifier } from "../../types/EndpointIdentifier";
import { CustomSnippetPayload } from "../../types/CustomSnippetPayload";

export const GetSnippetRequest: core.serialization.Schema<serializers.GetSnippetRequest.Raw, Fern.GetSnippetRequest> =
    core.serialization.object({
        orgId: OrgId.optional(),
        apiId: ApiId.optional(),
        sdks: core.serialization.list(Sdk).optional(),
        endpoint: EndpointIdentifier,
        payload: CustomSnippetPayload.optional(),
    });

export declare namespace GetSnippetRequest {
    interface Raw {
        orgId?: OrgId.Raw | null;
        apiId?: ApiId.Raw | null;
        sdks?: Sdk.Raw[] | null;
        endpoint: EndpointIdentifier.Raw;
        payload?: CustomSnippetPayload.Raw | null;
    }
}
