/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../..";
import * as Fern from "../../../api";
import * as core from "../../../core";
import { OrgId } from "../../resources/commons/types/OrgId";
import { ApiId } from "../../resources/commons/types/ApiId";
import { Sdk } from "../../types/Sdk";

export const ListSnippetsRequest: core.serialization.Schema<
    serializers.ListSnippetsRequest.Raw,
    Omit<Fern.ListSnippetsRequest, "page">
> = core.serialization.object({
    orgId: OrgId.optional(),
    apiId: ApiId.optional(),
    sdks: core.serialization.list(Sdk).optional(),
});

export declare namespace ListSnippetsRequest {
    interface Raw {
        orgId?: OrgId.Raw | null;
        apiId?: ApiId.Raw | null;
        sdks?: Sdk.Raw[] | null;
    }
}
