/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const EndpointMethod: core.serialization.Schema<serializers.EndpointMethod.Raw, Fern.EndpointMethod> =
    core.serialization.enum_(["PUT", "POST", "GET", "PATCH", "DELETE"]);

export declare namespace EndpointMethod {
    type Raw = "PUT" | "POST" | "GET" | "PATCH" | "DELETE";
}
