/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";
import { EndpointPath } from "./EndpointPath";
import { EndpointMethod } from "./EndpointMethod";

export const EndpointIdentifier: core.serialization.ObjectSchema<
    serializers.EndpointIdentifier.Raw,
    Fern.EndpointIdentifier
> = core.serialization.object({
    path: EndpointPath,
    method: EndpointMethod,
});

export declare namespace EndpointIdentifier {
    interface Raw {
        path: EndpointPath.Raw;
        method: EndpointMethod.Raw;
    }
}
