/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const EndpointPath: core.serialization.Schema<serializers.EndpointPath.Raw, Fern.EndpointPath> =
    core.serialization.string();

export declare namespace EndpointPath {
    type Raw = string;
}
