/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const EndpointIdentifier: core.serialization.ObjectSchema<
    serializers.snippets.EndpointIdentifier.Raw,
    Fern.snippets.EndpointIdentifier
> = core.serialization.object({
    path: core.serialization.lazy(async () => (await import("../../..")).snippets.EndpointPath),
    method: core.serialization.lazy(async () => (await import("../../..")).snippets.EndpointMethod),
});

export declare namespace EndpointIdentifier {
    interface Raw {
        path: serializers.snippets.EndpointPath.Raw;
        method: serializers.snippets.EndpointMethod.Raw;
    }
}
