/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const GoSnippet: core.serialization.ObjectSchema<serializers.snippets.GoSnippet.Raw, Fern.snippets.GoSnippet> =
    core.serialization.object({
        sdk: core.serialization.lazyObject(async () => (await import("../../..")).snippets.GoSdk),
        client: core.serialization.string(),
    });

export declare namespace GoSnippet {
    interface Raw {
        sdk: serializers.snippets.GoSdk.Raw;
        client: string;
    }
}
