/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const JavaSnippet: core.serialization.ObjectSchema<
    serializers.snippets.JavaSnippet.Raw,
    Fern.snippets.JavaSnippet
> = core.serialization.object({
    sdk: core.serialization.lazyObject(async () => (await import("../../..")).snippets.JavaSdk),
    asyncClient: core.serialization.property("async_client", core.serialization.string()),
    syncClient: core.serialization.property("sync_client", core.serialization.string()),
});

export declare namespace JavaSnippet {
    interface Raw {
        sdk: serializers.snippets.JavaSdk.Raw;
        async_client: string;
        sync_client: string;
    }
}
