/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const ParameterPayload: core.serialization.ObjectSchema<
    serializers.ParameterPayload.Raw,
    Fern.ParameterPayload
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.unknown(),
});

export declare namespace ParameterPayload {
    interface Raw {
        name: string;
        value?: unknown;
    }
}
