/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const PythonSdk: core.serialization.ObjectSchema<serializers.snippets.PythonSdk.Raw, Fern.snippets.PythonSdk> =
    core.serialization.object({
        package: core.serialization.string(),
        version: core.serialization.string(),
    });

export declare namespace PythonSdk {
    interface Raw {
        package: string;
        version: string;
    }
}
