/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";
import { RubySdk } from "./RubySdk";

export const RubySnippet: core.serialization.ObjectSchema<serializers.RubySnippet.Raw, Fern.RubySnippet> =
    core.serialization.object({
        sdk: RubySdk,
        client: core.serialization.string(),
    });

export declare namespace RubySnippet {
    interface Raw {
        sdk: RubySdk.Raw;
        client: string;
    }
}
