/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const Sdk: core.serialization.Schema<serializers.snippets.Sdk.Raw, Fern.snippets.Sdk> = core.serialization
    .union("type", {
        typescript: core.serialization.lazyObject(async () => (await import("../../..")).snippets.TypeScriptSdk),
        python: core.serialization.lazyObject(async () => (await import("../../..")).snippets.PythonSdk),
        go: core.serialization.lazyObject(async () => (await import("../../..")).snippets.GoSdk),
        java: core.serialization.lazyObject(async () => (await import("../../..")).snippets.JavaSdk),
    })
    .transform<Fern.snippets.Sdk>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace Sdk {
    type Raw = Sdk.Typescript | Sdk.Python | Sdk.Go | Sdk.Java;

    interface Typescript extends serializers.snippets.TypeScriptSdk.Raw {
        type: "typescript";
    }

    interface Python extends serializers.snippets.PythonSdk.Raw {
        type: "python";
    }

    interface Go extends serializers.snippets.GoSdk.Raw {
        type: "go";
    }

    interface Java extends serializers.snippets.JavaSdk.Raw {
        type: "java";
    }
}
