/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const SnippetsPage: core.serialization.ObjectSchema<
    serializers.snippets.SnippetsPage.Raw,
    Fern.snippets.SnippetsPage
> = core.serialization.object({
    next: core.serialization.string().optional(),
    snippets: core.serialization.record(
        core.serialization.lazy(async () => (await import("../../..")).snippets.EndpointPath),
        core.serialization.lazy(async () => (await import("../../..")).snippets.SnippetsByEndpointMethod)
    ),
});

export declare namespace SnippetsPage {
    interface Raw {
        next?: string | null;
        snippets: Record<serializers.snippets.EndpointPath.Raw, serializers.snippets.SnippetsByEndpointMethod.Raw>;
    }
}
