/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";
import { Snippet } from "./Snippet";
import { EndpointMethod } from "./EndpointMethod";

export const SnippetsByEndpointMethod: core.serialization.Schema<
    serializers.SnippetsByEndpointMethod.Raw,
    Fern.SnippetsByEndpointMethod
> = core.serialization.record(EndpointMethod, core.serialization.list(Snippet).optional());

export declare namespace SnippetsByEndpointMethod {
    type Raw = Record<EndpointMethod.Raw, Snippet.Raw[] | null | undefined>;
}
