/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";
import { EndpointPath } from "./EndpointPath";
import { SnippetsByEndpointMethod } from "./SnippetsByEndpointMethod";
import { Snippet } from "./Snippet";
import { EndpointMethod } from "./EndpointMethod";

export const SnippetsPage: core.serialization.ObjectSchema<serializers.SnippetsPage.Raw, Fern.SnippetsPage> =
    core.serialization.object({
        next: core.serialization.number().optional(),
        snippets: core.serialization.record(EndpointPath, SnippetsByEndpointMethod),
    });

export declare namespace SnippetsPage {
    interface Raw {
        next?: number | null;
        snippets: Record<EndpointPath.Raw, SnippetsByEndpointMethod.Raw>;
    }
}
