/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const TypeScriptSnippet: core.serialization.ObjectSchema<
    serializers.snippets.TypeScriptSnippet.Raw,
    Fern.snippets.TypeScriptSnippet
> = core.serialization.object({
    sdk: core.serialization.lazyObject(async () => (await import("../../..")).snippets.TypeScriptSdk),
    client: core.serialization.string(),
});

export declare namespace TypeScriptSnippet {
    interface Raw {
        sdk: serializers.snippets.TypeScriptSdk.Raw;
        client: string;
    }
}
