/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "..";

export interface JavaSnippet {
    sdk: Fern.JavaSdk;
    asyncClient: string;
    syncClient: string;
}
