/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "..";

export interface PythonSnippet {
    sdk: Fern.PythonSdk;
    asyncClient: string;
    syncClient: string;
}
