/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export interface CustomSnippetPayload {
    headers?: FernInternal.ParameterPayload[];
    pathParameters?: FernInternal.ParameterPayload[];
    queryParameters?: FernInternal.ParameterPayload[];
    requestBody?: unknown;
}
