/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../..";

export interface CustomSnippetPayload {
    headers?: Fern.ParameterPayload[];
    pathParameters?: Fern.ParameterPayload[];
    queryParameters?: Fern.ParameterPayload[];
    requestBody?: unknown;
}
