/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../..";

export interface EndpointIdentifier {
    path: Fern.EndpointPath;
    method: Fern.EndpointMethod;
}
