/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export interface GoSnippet {
    sdk: FernInternal.GoSdk;
    client: string;
}
