/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export interface JavaSnippet {
    sdk: FernInternal.JavaSdk;
    async_client: string;
    sync_client: string;
}
