/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../index";

export interface PythonSnippet {
    sdk: Fern.PythonSdk;
    async_client: string;
    sync_client: string;
}
