/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export interface PythonSnippet {
    sdk: FernInternal.PythonSdk;
    async_client: string;
    sync_client: string;
}
