/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export interface RubySnippet {
    sdk: FernInternal.RubySdk;
    client: string;
}
