/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export type Sdk =
    | FernInternal.Sdk.Typescript
    | FernInternal.Sdk.Python
    | FernInternal.Sdk.Go
    | FernInternal.Sdk.Ruby
    | FernInternal.Sdk.Java;

export declare namespace Sdk {
    interface Typescript extends FernInternal.TypeScriptSdk {
        type: "typescript";
    }

    interface Python extends FernInternal.PythonSdk {
        type: "python";
    }

    interface Go extends FernInternal.GoSdk {
        type: "go";
    }

    interface Ruby extends FernInternal.RubySdk {
        type: "ruby";
    }

    interface Java extends FernInternal.JavaSdk {
        type: "java";
    }
}
