/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../..";

export type Sdk =
    | Fern.snippets.Sdk.Typescript
    | Fern.snippets.Sdk.Python
    | Fern.snippets.Sdk.Go
    | Fern.snippets.Sdk.Java;

export declare namespace Sdk {
    interface Typescript extends Fern.snippets.TypeScriptSdk {
        type: "typescript";
    }

    interface Python extends Fern.snippets.PythonSdk {
        type: "python";
    }

    interface Go extends Fern.snippets.GoSdk {
        type: "go";
    }

    interface Java extends Fern.snippets.JavaSdk {
        type: "java";
    }
}
