/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export type SdkRequest =
    | FernInternal.SdkRequest.Typescript
    | FernInternal.SdkRequest.Python
    | FernInternal.SdkRequest.Go
    | FernInternal.SdkRequest.Ruby
    | FernInternal.SdkRequest.Java;

export declare namespace SdkRequest {
    interface Typescript extends FernInternal.TypeScriptSdkRequest {
        type: "typescript";
    }

    interface Python extends FernInternal.PythonSdkRequest {
        type: "python";
    }

    interface Go extends FernInternal.GoSdkRequest {
        type: "go";
    }

    interface Ruby extends FernInternal.RubySdkRequest {
        type: "ruby";
    }

    interface Java extends FernInternal.JavaSdkRequest {
        type: "java";
    }
}
