/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export type SnippetsByEndpointMethod = Record<FernInternal.EndpointMethod, FernInternal.Snippet[] | undefined>;
