/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../..";

export type SnippetsByEndpointMethod = Record<Fern.EndpointMethod, Fern.Snippet[] | undefined>;
