/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../..";

export type Snippet =
    | Fern.Snippet.Typescript
    | Fern.Snippet.Python
    | Fern.Snippet.Java
    | Fern.Snippet.Go
    | Fern.Snippet.Ruby;

export declare namespace Snippet {
    interface Typescript extends Fern.TypeScriptSnippet {
        type: "typescript";
    }

    interface Python extends Fern.PythonSnippet {
        type: "python";
    }

    interface Java extends Fern.JavaSnippet {
        type: "java";
    }

    interface Go extends Fern.GoSnippet {
        type: "go";
    }

    interface Ruby extends Fern.RubySnippet {
        type: "ruby";
    }
}
