/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../index";

export interface TypeScriptSnippet {
    sdk: Fern.TypeScriptSdk;
    client: string;
}
