/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export interface TypeScriptSnippet {
    sdk: FernInternal.TypeScriptSdk;
    client: string;
}
