/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as Fern from "../../../../../api";
import * as core from "../../../../../core";
import { OrgId } from "../../../commons/types/OrgId";
import { ApiId } from "../../../commons/types/ApiId";
import { ApiDefinitionId } from "../../../commons/types/ApiDefinitionId";
import { SnippetRegistryEntry } from "../../types/SnippetRegistryEntry";

export const RegisterSnippetTemplateBatchRequest: core.serialization.Schema<
    serializers.RegisterSnippetTemplateBatchRequest.Raw,
    Fern.RegisterSnippetTemplateBatchRequest
> = core.serialization.object({
    orgId: OrgId,
    apiId: ApiId,
    apiDefinitionId: ApiDefinitionId,
    snippets: core.serialization.list(SnippetRegistryEntry),
});

export declare namespace RegisterSnippetTemplateBatchRequest {
    interface Raw {
        orgId: OrgId.Raw;
        apiId: ApiId.Raw;
        apiDefinitionId: ApiDefinitionId.Raw;
        snippets: SnippetRegistryEntry.Raw[];
    }
}
