/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const SnippetNotFound: core.serialization.Schema<serializers.SnippetNotFound.Raw, string> =
    core.serialization.string();

export declare namespace SnippetNotFound {
    type Raw = string;
}
