/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../..";

export interface EndpointSnippetTemplate {
    sdk: Fern.Sdk;
    endpointId: Fern.EndpointIdentifier;
    snippetTemplate: Fern.VersionedSnippetTemplate;
}
