/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export interface EndpointSnippetTemplate {
    sdk: FernInternal.Sdk;
    endpointId: FernInternal.EndpointIdentifier;
    snippetTemplate: FernInternal.VersionedSnippetTemplate;
}
