/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export interface PayloadInput {
    location: FernInternal.PayloadLocation;
    /** Dot delimited path to the value within the payload, if omitted the full payload is used. */
    path?: string;
}
