/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export interface SnippetRegistryEntry {
    sdk: FernInternal.Sdk;
    endpointId: FernInternal.EndpointIdentifier;
    snippetTemplate: FernInternal.VersionedSnippetTemplate;
}
