/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../index";

export interface SnippetTemplate {
    clientInstantiation: Fern.ClientInstantiation;
    functionInvocation: Fern.Template;
}
