/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export interface SnippetTemplate {
    clientInstantiation: string;
    functionInvocation: FernInternal.Template;
}
