/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export type Template =
    | FernInternal.Template.Generic
    | FernInternal.Template.Enum
    | FernInternal.Template.DiscriminatedUnion
    | FernInternal.Template.Union
    | FernInternal.Template.Dict
    | FernInternal.Template.Iterable;

export declare namespace Template {
    interface Generic extends FernInternal.GenericTemplate {
        type: "generic";
    }

    interface Enum extends FernInternal.EnumTemplate {
        type: "enum";
    }

    interface DiscriminatedUnion extends FernInternal.DiscriminatedUnionTemplate {
        type: "discriminatedUnion";
    }

    interface Union extends FernInternal.UnionTemplate {
        type: "union";
    }

    interface Dict extends FernInternal.DictTemplate {
        type: "dict";
    }

    interface Iterable extends FernInternal.IterableTemplate {
        type: "iterable";
    }
}
