/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../index";

export interface UnionTemplateMember {
    type: Fern.api.v1.read.TypeReference;
    template: Fern.Template;
}
