/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../index";

export type VersionedSnippetTemplate = Fern.VersionedSnippetTemplate.V1;

export declare namespace VersionedSnippetTemplate {
    interface V1 extends Fern.SnippetTemplate {
        type: "v1";
    }
}
