/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../../index";

export type VersionedSnippetTemplate = FernInternal.VersionedSnippetTemplate.V1;

export declare namespace VersionedSnippetTemplate {
    interface V1 extends FernInternal.SnippetTemplate {
        type: "v1";
    }
}
