/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Fern from "../../api";
import * as core from "../../core";
import { GoSdk } from "./GoSdk";

export const GoSnippet: core.serialization.ObjectSchema<serializers.GoSnippet.Raw, Fern.GoSnippet> =
    core.serialization.object({
        sdk: GoSdk,
        client: core.serialization.string(),
    });

export declare namespace GoSnippet {
    interface Raw {
        sdk: GoSdk.Raw;
        client: string;
    }
}
