/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Fern from "../../api";
import * as core from "../../core";

export const RubySdk: core.serialization.ObjectSchema<serializers.RubySdk.Raw, Fern.RubySdk> =
    core.serialization.object({
        gem: core.serialization.string(),
        version: core.serialization.string(),
    });

export declare namespace RubySdk {
    interface Raw {
        gem: string;
        version: string;
    }
}
