/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as Fern from "../../api";
import * as core from "../../core";
import { TypeScriptSdk } from "./TypeScriptSdk";

export const TypeScriptSnippet: core.serialization.ObjectSchema<
    serializers.TypeScriptSnippet.Raw,
    Fern.TypeScriptSnippet
> = core.serialization.object({
    sdk: TypeScriptSdk,
    client: core.serialization.string(),
});

export declare namespace TypeScriptSnippet {
    interface Raw {
        sdk: TypeScriptSdk.Raw;
        client: string;
    }
}
