/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export interface ListType {
    itemType: Fern.api.v1.read.TypeReference;
}
