/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export type LiteralType = Fern.api.v1.read.LiteralType.BooleanLiteral | Fern.api.v1.read.LiteralType.StringLiteral;

export declare namespace LiteralType {
    interface BooleanLiteral {
        type: "booleanLiteral";
        value: boolean;
    }

    interface StringLiteral {
        type: "stringLiteral";
        value: string;
    }
}
