/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export interface MapType {
    keyType: Fern.api.v1.read.TypeReference;
    valueType: Fern.api.v1.read.TypeReference;
}
