/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export interface OptionalType {
    itemType: Fern.api.v1.read.TypeReference;
    defaultValue?: unknown;
}
