/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export type PrimitiveType =
    | Fern.api.v1.read.PrimitiveType.Integer
    | Fern.api.v1.read.PrimitiveType.Double
    | Fern.api.v1.read.PrimitiveType.String
    | Fern.api.v1.read.PrimitiveType.Long
    | Fern.api.v1.read.PrimitiveType.Boolean
    | Fern.api.v1.read.PrimitiveType.Datetime
    | Fern.api.v1.read.PrimitiveType.Uuid
    | Fern.api.v1.read.PrimitiveType.Base64
    | Fern.api.v1.read.PrimitiveType.Date_
    | Fern.api.v1.read.PrimitiveType.BigInteger
    | Fern.api.v1.read.PrimitiveType.Uint
    | Fern.api.v1.read.PrimitiveType.Uint64;

export declare namespace PrimitiveType {
    interface Integer extends Fern.api.v1.read.IntegerType {
        type: "integer";
    }

    interface Double extends Fern.api.v1.read.DoubleType {
        type: "double";
    }

    interface String extends Fern.api.v1.read.StringType {
        type: "string";
    }

    interface Long extends Fern.api.v1.read.LongType {
        type: "long";
    }

    interface Boolean extends Fern.api.v1.read.BooleanType {
        type: "boolean";
    }

    interface Datetime extends Fern.api.v1.read.DatetimeType {
        type: "datetime";
    }

    interface Uuid extends Fern.api.v1.read.UuidType {
        type: "uuid";
    }

    interface Base64 extends Fern.api.v1.read.Base64Type {
        type: "base64";
    }

    interface Date_ extends Fern.api.v1.read.DateType {
        type: "date";
    }

    interface BigInteger extends Fern.api.v1.read.BigIntegerType {
        type: "bigInteger";
    }

    interface Uint {
        type: "uint";
    }

    interface Uint64 {
        type: "uint64";
    }
}
