/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export interface TypeReferenceId {
    value: Fern.TypeId;
    default?: Fern.api.v1.read.TypeReferenceIdDefault;
}
