/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export type TypeReference =
    | Fern.api.v1.read.TypeReference.Id
    | Fern.api.v1.read.TypeReference.Primitive
    | Fern.api.v1.read.TypeReference.Optional
    | Fern.api.v1.read.TypeReference.List
    | Fern.api.v1.read.TypeReference.Set
    | Fern.api.v1.read.TypeReference.Map
    | Fern.api.v1.read.TypeReference.Literal
    | Fern.api.v1.read.TypeReference.Unknown;

export declare namespace TypeReference {
    interface Id extends Fern.api.v1.read.TypeReferenceId {
        type: "id";
    }

    interface Primitive {
        type: "primitive";
        value: Fern.api.v1.read.PrimitiveType;
    }

    interface Optional extends Fern.api.v1.read.OptionalType {
        type: "optional";
    }

    interface List extends Fern.api.v1.read.ListType {
        type: "list";
    }

    interface Set extends Fern.api.v1.read.SetType {
        type: "set";
    }

    interface Map extends Fern.api.v1.read.MapType {
        type: "map";
    }

    interface Literal {
        type: "literal";
        value: Fern.api.v1.read.LiteralType;
    }

    interface Unknown {
        type: "unknown";
    }
}
