/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../../../../../../index";

export type TypeReferenceIdDefault = Fern.api.v1.read.TypeReferenceIdDefault.Enum;

export declare namespace TypeReferenceIdDefault {
    interface Enum {
        type: "enum";
        value: string;
    }
}
