/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../..";

/**
 * @example
 *     {
 *         endpoint: {
 *             method: Fern.snippets.EndpointMethod.Get,
 *             path: "/v1/search"
 *         }
 *     }
 */
export interface GetSnippetRequest {
    /**
     * If the same API is defined across multiple organization,
     * you must specify an organization ID.
     *
     */
    orgId?: Fern.snippets.OrgId;
    /**
     * If you have more than one API, you must specify its ID.
     *
     */
    apiId?: Fern.snippets.ApiId;
    /**
     * The SDKs for which to load snippets. If unspecified,
     * snippets for the latest published SDKs will be returned.
     *
     */
    sdks?: Fern.snippets.Sdk[];
    endpoint: Fern.snippets.EndpointIdentifier;
}
