/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../..";

export interface ListSnippetsRequest {
    page?: number;
    /**
     * If the same API is defined across multiple organization,
     * you must specify an organization ID.
     *
     */
    orgId?: Fern.snippets.OrgId;
    /**
     * If you have more than one API, you must specify its ID.
     *
     */
    apiId?: Fern.snippets.ApiId;
    /**
     * The SDKs for which to load snippets. If unspecified,
     * snippets for the latest published SDKs will be returned.
     *
     */
    sdks?: Fern.snippets.Sdk[];
}
