/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../../../errors";

export class UserNotInOrgError extends errors.FernError {
    constructor() {
        super({
            message: "UserNotInOrgError",
            statusCode: 403,
        });
        Object.setPrototypeOf(this, UserNotInOrgError.prototype);
    }
}
