/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as core from "../../../../core";

export const UnauthorizedError: core.serialization.Schema<serializers.UnauthorizedError.Raw, string> =
    core.serialization.string();

export declare namespace UnauthorizedError {
    type Raw = string;
}
