/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class ApiIdNotFound extends errors.FernError {
    constructor() {
        super({
            statusCode: 404,
        });
        Object.setPrototypeOf(this, ApiIdNotFound.prototype);
    }
}
