/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class ApiIdNotFound extends errors.FernError {
    constructor(body: string) {
        super({
            message: "ApiIdNotFound",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, ApiIdNotFound.prototype);
    }
}
