/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class EndpointNotFound extends errors.FernInternalError {
    constructor(body: string) {
        super({
            message: "EndpointNotFound",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, EndpointNotFound.prototype);
    }
}
