/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors";

export class OrgIdNotFound extends errors.FernError {
    constructor(body: string) {
        super({
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, OrgIdNotFound.prototype);
    }
}
