/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";

export class OrgIdAndApiIdNotFound extends errors.FernError {
    constructor(body: string) {
        super({
            message: "OrgIdAndApiIdNotFound",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, OrgIdAndApiIdNotFound.prototype);
    }
}
