/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as FernInternal from "../../..";

export interface EndpointIdentifier {
    path: FernInternal.EndpointPath;
    method: FernInternal.EndpointMethod;
}
