/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Templates } from "./api/resources/templates/client/Client";
import { SnippetsExtended } from "api/resources/snippets/client/ClientExtended";

export declare namespace FernClient {
    interface Options {
        environment?: core.Supplier<environments.FernEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }

    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}

export class FernClient {
    constructor(protected readonly _options: FernClient.Options = {}) {}

    protected _snippets: SnippetsExtended | undefined;

    public get snippets(): SnippetsExtended {
        return (this._snippets ??= new SnippetsExtended(this._options));
    }

    protected _templates: Templates | undefined;

    public get templates(): Templates {
        return (this._templates ??= new Templates(this._options));
    }
}
