/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FernInternalEnvironment = {
    Dev: "https://registry-dev2.buildwithfern.com",
    Prod: "https://registry.buildwithfern.com",
} as const;

export type FernInternalEnvironment = typeof FernInternalEnvironment.Dev | typeof FernInternalEnvironment.Prod;
