/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FernEnvironment = {
    Dev: "https://registry-dev2.buildwithfern.com",
    Prod: "https://registry.buildwithfern.com",
} as const;

export type FernEnvironment = typeof FernEnvironment.Dev | typeof FernEnvironment.Prod;
