/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const FernEnvironment = {
    Production: "https://api.buildwithfern.com",
} as const;

export type FernEnvironment = typeof FernEnvironment.Production;
