/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Fern from "../../../../index";

/**
 * @example
 *     {
 *         orgId: "string",
 *         tokenId: "string"
 *     }
 */
export interface RevokeTokenRequest {
    /**
     * The organization to create snippets for.
     *
     */
    orgId: Fern.OrgId;
    tokenId: Fern.TokenId;
}
