/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const ApiDefinitionId: core.serialization.Schema<serializers.ApiDefinitionId.Raw, Fern.ApiDefinitionId> =
    core.serialization.string();

export declare namespace ApiDefinitionId {
    type Raw = string;
}
