/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as Fern from "../../../../api";
import * as core from "../../../../core";

export const ApiId: core.serialization.Schema<serializers.ApiId.Raw, Fern.ApiId> = core.serialization.string();

export declare namespace ApiId {
    type Raw = string;
}
